= FeatureHub SDK for REST clients

== Overview
This SDK operates using periodic REST requests. It should be used typically
in client libraries when near-real-time updates are not required. It operates
on a timeout + use based context where you can set a refresh period, and it
will ignore any attempts to poll for new updates outside of that timeout period.
Any request to evaluate a feature will automatically cause an attempt to poll,
so use of your application will cause features to update within the time period,
whereas lack of use will not consume any bandwidth.

It is therefore up to you as to how "fresh" you wish to keep your features, 
with the knowledge that once that freshness timeout has been exceeded and 
the app is evaluating features, it will re-request the feature state.

== Considerations

=== Library Dependencies

This library uses:

- OKHttp 4 (for http)
- Jackson 2.x (for json)
- SLF4j (for logging)

If you need your Android client to use another technology, please let us know or feel free to contribute another version.

Visit our official web page for more information about the platform https://www.featurehub.io/[here]

=== Using on Android

As it requires internet access, you will need to add to your `AndroidManifest.xml` the usual:

`<uses-permission android:name="android.permission.INTERNET"/>`

If you are using it locally and not behind https, you will also need to specify an attribute on your `<application>` tag,
which allows clear text traffic.

`android:usesCleartextTraffic="true"`

You will need to store your repository in a central location, using a static or via a DI tool like Dagger.Using a static
might look something like this:

Core uses Java's ServiceLoader capability to automatically discover the JerseyClient implementation. Please
simply follow the instructions in the https://github.com/featurehub-io/featurehub-java-sdk/tree/main/client-java-core[Java Core library].

As per that documentation you can manually configure the Edge provider to be the `AndroidFeatureHubClientFactory` if 
you wish.
