/*
 * Todo
 * Sample todo-api
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.featurehub.examples.springboot;

import com.fasterxml.jackson.annotation.*;
import java.time.OffsetDateTime;
import java.util.Objects;

/** Todo */
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(
    value = "cd.connect.openapi.Jersey3ApiGenerator",
    date = "2026-01-11T09:21:49.181170+13:00[Pacific/Auckland]")
public class Todo {
  @JsonProperty("id")
  // required true nullable true default
  @org.jetbrains.annotations.Nullable
  private String id;

  @JsonProperty("title")
  // required false nullable false default
  @org.jetbrains.annotations.NotNull
  private String title;

  @JsonProperty("resolved")
  // required false nullable true default
  @org.jetbrains.annotations.Nullable
  private Boolean resolved;

  @JsonProperty("when")
  // required false nullable true default
  @org.jetbrains.annotations.Nullable
  private OffsetDateTime when;

  public Todo id(@org.jetbrains.annotations.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @org.jetbrains.annotations.Nullable
  public String getId() {
    return id;
  }

  public void setId(@org.jetbrains.annotations.Nullable String id) {
    this.id = id;
  }

  public Todo title(@org.jetbrains.annotations.NotNull String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   *
   * @return title
   */
  @org.jetbrains.annotations.NotNull
  public String getTitle() {
    return title;
  }

  public void setTitle(@org.jetbrains.annotations.NotNull String title) {
    this.title = title;
  }

  public Todo resolved(@org.jetbrains.annotations.Nullable Boolean resolved) {
    this.resolved = resolved;
    return this;
  }

  /**
   * Get resolved
   *
   * @return resolved
   */
  @org.jetbrains.annotations.Nullable
  public Boolean getResolved() {
    return resolved;
  }

  public void setResolved(@org.jetbrains.annotations.Nullable Boolean resolved) {
    this.resolved = resolved;
  }

  public Todo when(@org.jetbrains.annotations.Nullable OffsetDateTime when) {
    this.when = when;
    return this;
  }

  /**
   * Get when
   *
   * @return when
   */
  @org.jetbrains.annotations.Nullable
  public OffsetDateTime getWhen() {
    return when;
  }

  public void setWhen(@org.jetbrains.annotations.Nullable OffsetDateTime when) {
    this.when = when;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Todo todo = (Todo) o;
    return Objects.equals(this.id, todo.id)
        && Objects.equals(this.title, todo.title)
        && Objects.equals(this.resolved, todo.resolved)
        && Objects.equals(this.when, todo.when);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, resolved, when);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Todo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    resolved: ").append(toIndentedString(resolved)).append("\n");
    sb.append("    when: ").append(toIndentedString(when)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public Todo copy() {
    Todo copy = new Todo();

    copy.setId(this.getId());
    copy.setTitle(this.getTitle());
    copy.setResolved(this.getResolved());
    copy.setWhen(this.getWhen());

    return copy;
  }
}
